image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

install:
  stage: build
  script:
    - yarn

lint:
  stage: test
  script:
    - yarn test:lint

unit:
  stage: test
  script:
    - yarn test:unit

integration:
  stage: test
  script:
    - yarn test:integration

tag:
  before_script:
    - yarn global add @wondermonger/version
  only: master
  script:
    - export PKG_VERSION=$(git fetch | version)
    - npm version ${PKG_VERSION} -m "[ci skip] update version to %s"
    - git push --follow-tags
  stage: deploy
