image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

install:
  stage: build
  script:
    - yarn

lint:
  stage: test
  script:
    - yarn test:lint

unit:
  stage: test
  script:
    - yarn test:unit

integration:
  stage: test
  script:
    - yarn test:integration

release:
  before_script:
    - git config --global user.email "${ACCESS_EMAIL}"
    - git config --global user.name "${ACCESS_NAME}"
    - yarn config set version-git-message "release v%s"
  only:
    - master
  script:
    - git checkout master
    - yarn version --new-version patch
    - yarn version --no-git-tag-version --new-version prerelease
    - export PRERELEASE_VERSION=$(node -p "require('./package.json').version")
    - git add package.json
    - git commit -m "[ci skip] prerelease v${PRERELEASE_VERSION}"
    - git push --follow-tags $CI_REPOSITORY_URL HEAD:$CI_COMMIT_REF_NAME
  stage: deploy
  variables:
    CI_REPOSITORY_URL: https://$ACCESS_USER:$ACCESS_TOKEN@gitlab.com/$CI_PROJECT_PATH.git

publish:
  # only:
  #   - tags
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - npm publish
  stage: deploy
