image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - coverage
  - deploy

install:
  script:
    - yarn
  stage: build

lint:
  script:
    - yarn lint
  stage: test

test:
  script:
    - yarn test
  stage: test
